name: Test and Deploy on Tag

on:
  push:
    tags:
      - '*' 
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

  pre-deploy:
    name: Pre-Deploy Checks
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Perform pre-deployment checks
        run: |
          # Insérez ici vos vérifications pré-déploiement, comme des tests d'intégration, des analyses de code, etc.

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: pre-deploy
    environment: production

    steps:
      - name: Get current tag
        id: current_tag
        run: echo "::set-output name=current_tag::${{ github.ref }}"

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            git checkout ${{ github.ref }}
            composer install --no-dev --optimize-autoloader
            php bin/console cache:clear --env=prod
            php bin/console doctrine:migrations:migrate --no-interaction --env=prod
            php bin/console assets:install

# Définition de l'action de rollback en cas d'erreur dans le déploiement
  rollback:
    name: Rollback on Deployment Failure
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()

    steps:
      - name: Revert to previous production version
        run: |
          cd ${{ secrets.PROJECT_PATH }}
          git fetch --tags
          git checkout ${{ steps.current_tag.outputs.current_tag }}
