name: Test and Deploy on Tag

on:
  push:
    tags:
      - '*' 
    branches:
      - main

jobs:
  call-tests:
    uses: ./.github/workflows/test_steps.yml
      
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: call-tests
    environment: production

    steps:
      - name: Get current tag
        id: current_tag
        run: echo "current_tag=${{ github.ref }}" >> "$GITHUB_ENV"

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ${{ secrets.PROJECT_PATH }}
            git fetch --all --tags
            git checkout ${{ github.ref }}
            composer install --no-dev --optimize-autoloader
            php bin/console cache:clear --env=prod
            php bin/console doctrine:migrations:migrate --no-interaction --env=prod
            php bin/console assets:install

# Définition de l'action de rollback en cas d'erreur dans le déploiement
  rollback:
    name: Rollback on Deployment Failure
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    environment: production

    steps:
      - name: Revert to previous production version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git fetch --all --tags
            git checkout $current_tag
            composer install --no-dev --optimize-autoloader
            php bin/console cache:clear --env=prod
            php bin/console doctrine:migrations:migrate --no-interaction --env=prod
            php bin/console assets:install

