name: Test on PR
on:
  pull_request:
    types:
      - opened

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      # Inclusion des étapes de test définies dans l'ancre 'test_steps'
      <<: *test_steps
   